### ISSUE TITLE
缺少jar包

### ISSUE THREAD

**Issue by yyingcan** [ggj2010/redis#1]
项目导入缺少jar包，请问能不能给jar包一块上传呢

**Comment by ggj2010** [comment]
这是maven项目，你用maven构建就可以了

**Comment by yyingcan** [comment]
mvn clean install -Dmaven.test.skip=true 这样吗？我的老是报错，是不是网络的问题？在下新手，还望多指教

**Comment by yyingcan** [comment]
但是在你的pom 文件中 有继承 
       <parent>
        <groupId>cn.msec.common.platform</groupId>
        <artifactId>pom.parent</artifactId>
        <version>0.1.0</version>
    </parent>
在源码中找不到被继承的xml
