### ISSUE TITLE
性能不快反而慢

### ISSUE THREAD

**Issue by wanyuncheng1993** [ggj2010/redis#4]
模拟了5000份数据，用项目里面的测试用例，执行时间差距基本可以忽略不计，但select all 的时候要比mysql慢很多。
是我测试方法的问题还是本身如此？

**Comment by ggj2010** [comment]
如果mysql开启了查询缓存， 数据量不大的情况下执行时间应该差距不大的。

**Comment by wanyuncheng1993** [comment]
抽取的是测试库的用户信息（单表），共20000+，试跑一下，会有明显的假死
5000条运行时间在可接受范围内
循环有点简单粗暴了
感谢分享，还是给了很多思路
